# [Q2] Format the above data like this:

# =================================
# DEPLOYMENT RECEIPT
# =================================
# Repository : cicd

# Branch : main

# Triggered By : swapnil

# Event Type : push

# Timestamp : Mon Jun 8 14:12:08 UTC 2026
# =================================


name: Formatted Receipt Workflow

on: 
 push:
  branches:  
      - main

jobs:
 print-details: 
  runs-on: ubuntu-latest

  steps:
  - name: Print Deployment Receipt
    run: |
     TIMESTAMP=$(date)
     echo "================================="
        echo "        DEPLOYMENT RECEIPT"
        echo "================================="
        echo ""
        echo "Repository   : ${{ github.event.repository.name }}"
        echo "Branch       : ${{ github.ref_name }}"
        echo "Triggered By : ${{ github.actor }}"
        echo "Event Type   : ${{ github.event_name }}"
        echo ""
        echo "Timestamp    : $TIMESTAMP"
        echo ""
        echo "================================="